# Generated by Django 3.1.4 on 2020-12-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201202_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
    ]
